{
  "name": "royal-md",
  "version": "4.0.0",
  "description": "l'instance dans l'ombre - Bot WhatsApp Royal MD",
  "main": "index.js",
  "type": "commonjs",  // Défini comme commonjs pour require, si vous utilisez import/export en haut de index.js, changez en "module"
  "scripts": {
    "start": "pm2 start index.js --deep-monitoring --attach --name royal-md",
    "stop": "pm2 stop royal-md",  // Correction pour correspondre au nom "royal-md"
    "restart": "pm2 restart royal-md"
  },
  "dependencies": {
    "@whiskeysockets/baileys": "6.7.9",
    "qrcode-terminal": "^0.12.0",
    "uuid": "^9.0.1",              
    "pino": "^7.0.5",
    "pm2": "^6.0.5",               
    "node-fetch": "^2.7.0",         
    "fs-extra": "^11.1.0",         
    "dotenv": "^16.4.7",            
    "path": "^0.12.7",             
    "util": "^0.12.5",              
    "os": "^0.1.2",                 
    "crypto": "^1.0.1",             
    "axios": "^1.2.5",             
    "file-type": "^16.5.3",         
    "fluent-ffmpeg": "^2.1.2",      
    "wa-sticker-formatter": "^4.4.4",
    "megajs": "^1.1.0",             
    
    "bochilteam/scraper": "3.0.0",
    "neeraj-x0/textpro": "^1.0.3",
    "vitalets/google-translate-api": "^9.2.0",
    "adiwajshing/keyed-db": "^0.2.4",
    "dark-yasiya/yt-dl.js":"latest", 
    "dark-yasiya/scrap":"1.0.1",
    "ffmpeg-installer/ffmpeg": "^1.1.0",
    "mumaker": "^2.0.0",
    "node-cron": "^3.0.2",
    "node-schedule": "^2.1.0",
    "node-webpmux": "^3.1.0",
    "pg": "^8.8.0",
    "archiver": "^5.3.1",
    "bitly": "^7.1.2",
    "jimp": "^0.16.1",
    "module-alias": "^2.2.3",
    "jsdom": "^20.0.0",
    "lodash": "^4.17.21",
    "browser-id3-writer": "^4.4.0",
    "express": "latest",
    "crypto-digest-sync": "^1.0.0",
    "crypto-js": "latest",
    "file_size_url": "1.0.4",
    "g-i-s": "^2.1.6",
    "google-tts-api": "^2.0.2",
    "got": "^11.8.2",
    "heroku-client": "^3.1.0",
    "imgbb-uploader": "^1.5.1",
    "ffmpeg": "^0.0.4",
    "form-data": "^4.0.1",
    "btch-downloader": "^2.2.9",
    "wa_set_pkg": "1.0.5",
    "adm-zip": "^0.4.16",
    "cheerio": "^1.0.0-rc.12",
    "ruhend-scraper" : "8.0.3",
    "yt-search":"2.11.1",
    "moment-timezone": "^0.5.40",
    "raganork-bot": "^3.0.1",
    "scraper-x0": "^1.0.6",
    "sequelize": "^6.23.0",
    "simple-git": "^3.14.1",
    "spinnies": "^0.5.1",
    "sqlite": "^5.1.1",
    "sqlite3": "^5.1.7",
    "supervisor": "^0.12.0",
    "vm": "^0.1.0",
    "api-dylux":"1.8.5",
    "mrnima/tiktok-downloader":"1.0.0",
    "mrnima/facebook-downloader":"1.0.0",
    "mrnima-moviedl":"1.0.0",
    "body-parser": "^1.20.2"
  }
      }
    
